name: Build old worksheets (libreoffice)

on: [push]

permissions:
  # To allow creating releases and attaching artifacts to it.
  contents: write

jobs:
  linux-build:
    name: Build old worksheets (libreoffice)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Update and install packages
        run: |
          sudo apt-get update
          sudo apt-get install libreoffice poppler-utils zip
      - name: Convert english sheets
        run: |
          pushd old/en
          for file in *.fodt; do libreoffice --convert-to pdf $file; done
          zip python-sheets-old-en.zip *.pdf
          popd
      - name: Convert french sheets
        run: |
          pushd old/fr
          for file in *.fodt; do libreoffice --convert-to pdf $file; done
          zip python-sheets-old-fr.zip *.pdf
          popd
      - name: Check PDF files
        run: |
          if file old/*/*.pdf | grep -v "1 page"
          then
            echo "Some PDFs have more than 1 page!"
            exit 1
          fi
      - name: Merged versions
        run: |
          pushd old
          for lang in fr en
          do
            pushd $lang
            pdfunite *.pdf python-sheets-old-${lang}.pdf
            popd
          done
          popd
      # Ensure tag is updated, so that the date shown on the release is recent.
      - uses: richardsimko/update-tag@v3
        with:
          tag_name: latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish zips and pdfs
        uses: softprops/action-gh-release@v3
        with:
          name: latest
          tag_name: latest
          body: Latest version of the sheets / Dernière version des fiches
          files: |
            old/en/python-sheets-old-en.zip
            old/fr/python-sheets-old-fr.zip
            old/en/python-sheets-old-en.pdf
            old/fr/python-sheets-old-fr.pdf
          fail_on_unmatched_files: true
          draft: false
          prerelease: false
          make_latest: true
          token: ${{ secrets.GITHUB_TOKEN }}
